version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2obupc4qyrer"
s3_prefix = "sam-app"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
